// Source: llm-inference-planner/catalog/models.yaml — keep in sync manually
import type { HFModelConfig } from '@/lib/huggingface/fetch-config'
import type { RooflineModel } from './roofline-types'

function kv(layers: number, kvHeads: number, headDim: number, kvDtypeBytes: number): number {
  return 2 * layers * kvHeads * headDim * kvDtypeBytes
}

export const ROOFLINE_MODEL_CATALOG: RooflineModel[] = [
  // ── Llama family ─────────────────────────────────────────────────────────────
  {
    id: 'llama-2-70b',
    hfId: 'meta-llama/Llama-2-70b-chat-hf',
    display_name: 'Llama 2 70B',
    is_moe: false,
    total_params: 69_924_000_000,
    active_params: 69_924_000_000,
    num_layers: 80,
    d_model: 8192,
    num_q_heads: 64,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(80, 8, 128, 2),
    geometry_source: 'known',
  },
  {
    id: 'llama-3.1-8b',
    hfId: 'meta-llama/Llama-3.1-8B-Instruct',
    display_name: 'Llama 3.1 8B',
    is_moe: false,
    total_params: 8_030_000_000,
    active_params: 8_030_000_000,
    num_layers: 32,
    d_model: 4096,
    num_q_heads: 32,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(32, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'llama-3.1-70b',
    hfId: 'meta-llama/Llama-3.1-70B-Instruct',
    display_name: 'Llama 3.1 70B',
    is_moe: false,
    total_params: 70_600_000_000,
    active_params: 70_600_000_000,
    num_layers: 80,
    d_model: 8192,
    num_q_heads: 64,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(80, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'llama-3.3-70b',
    hfId: 'meta-llama/Llama-3.3-70B-Instruct',
    display_name: 'Llama 3.3 70B',
    is_moe: false,
    total_params: 70_600_000_000,
    active_params: 70_600_000_000,
    num_layers: 80,
    d_model: 8192,
    num_q_heads: 64,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(80, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'llama-4-maverick',
    hfId: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct',
    display_name: 'Llama 4 Maverick',
    is_moe: true,
    total_params: 400_000_000_000,
    active_params: 52_000_000_000,
    num_experts: 128,
    experts_per_token: 8,
    num_layers: 48,
    d_model: 5120,
    num_q_heads: 40,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(48, 8, 128, 1),
    geometry_source: 'estimated',
  },
  // ── Gemma 2 ──────────────────────────────────────────────────────────────────
  {
    id: 'gemma-2-9b',
    hfId: 'google/gemma-2-9b-it',
    display_name: 'Gemma 2 9B',
    is_moe: false,
    total_params: 9_240_000_000,
    active_params: 9_240_000_000,
    num_layers: 42,
    d_model: 3584,
    num_q_heads: 16,
    num_kv_heads: 8,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(42, 8, 256, 2),
    geometry_source: 'known',
    sliding_window: 4096,
    global_layer_every_n: 2,
  },
  // ── Gemma 3 ──────────────────────────────────────────────────────────────────
  // head_dim=256 for 1B/4B/12B (ATYPICAL). Interleaved: 5 local per 1 global (every 6th is global).
  {
    id: 'gemma-3-1b',
    hfId: 'google/gemma-3-1b-it',
    display_name: 'Gemma 3 1B',
    is_moe: false,
    total_params: 1_000_000_000,
    active_params: 1_000_000_000,
    num_layers: 26,
    d_model: 1152,
    num_q_heads: 4,
    num_kv_heads: 1,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(26, 1, 256, 2),
    geometry_source: 'known',
    sliding_window: 512,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-3-4b',
    hfId: 'google/gemma-3-4b-it',
    display_name: 'Gemma 3 4B',
    is_moe: false,
    total_params: 4_300_000_000,
    active_params: 4_300_000_000,
    num_layers: 34,
    d_model: 2560,
    num_q_heads: 8,
    num_kv_heads: 4,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(34, 4, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-3-12b',
    hfId: 'google/gemma-3-12b-it',
    display_name: 'Gemma 3 12B',
    is_moe: false,
    total_params: 12_000_000_000,
    active_params: 12_000_000_000,
    num_layers: 48,
    d_model: 3840,
    num_q_heads: 16,
    num_kv_heads: 8,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(48, 8, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-3-27b',
    hfId: 'google/gemma-3-27b-it',
    display_name: 'Gemma 3 27B',
    is_moe: false,
    total_params: 27_200_000_000,
    active_params: 27_200_000_000,
    num_layers: 62,
    d_model: 5376,
    num_q_heads: 32,
    num_kv_heads: 16,
    head_dim: 128,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(62, 16, 128, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  // ── Gemma 4 ──────────────────────────────────────────────────────────────────
  // Global layers (every 6th) use head_dim=512 and different KV heads — engine uses
  // local-layer values (conservative: global-layer KV is underestimated).
  {
    id: 'gemma-4-e2b',
    hfId: 'google/gemma-4-e2b-it',
    display_name: 'Gemma 4 E2B',
    is_moe: false,
    total_params: 2_000_000_000,
    active_params: 2_000_000_000,
    num_layers: 35,
    d_model: 1536,
    num_q_heads: 8,
    num_kv_heads: 1,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(35, 1, 256, 2),
    geometry_source: 'known',
    sliding_window: 512,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-4-e4b',
    hfId: 'google/gemma-4-e4b-it',
    display_name: 'Gemma 4 E4B',
    is_moe: false,
    total_params: 4_000_000_000,
    active_params: 4_000_000_000,
    num_layers: 42,
    d_model: 2560,
    num_q_heads: 8,
    num_kv_heads: 2,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(42, 2, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-4-12b',
    hfId: 'google/gemma-4-12b-it',
    display_name: 'Gemma 4 12B',
    is_moe: false,
    total_params: 12_000_000_000,
    active_params: 12_000_000_000,
    num_layers: 48,
    d_model: 3840,
    num_q_heads: 16,
    num_kv_heads: 8,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(48, 8, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-4-26b-a4b',
    hfId: 'google/gemma-4-26b-it',
    display_name: 'Gemma 4 26B-A4B',
    is_moe: true,
    total_params: 26_000_000_000,
    active_params: 4_000_000_000,
    num_experts: 128,
    experts_per_token: 8,
    num_layers: 30,
    d_model: 2816,
    num_q_heads: 16,
    num_kv_heads: 8,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(30, 8, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  {
    id: 'gemma-4-31b',
    hfId: 'google/gemma-4-31b-it',
    display_name: 'Gemma 4 31B',
    is_moe: false,
    total_params: 31_000_000_000,
    active_params: 31_000_000_000,
    num_layers: 60,
    d_model: 5376,
    num_q_heads: 32,
    num_kv_heads: 16,
    head_dim: 256,
    kv_dtype_bytes: 2,
    kv_bytes_per_token: kv(60, 16, 256, 2),
    geometry_source: 'known',
    sliding_window: 1024,
    global_layer_every_n: 6,
  },
  // ── Mistral family ────────────────────────────────────────────────────────────
  {
    id: 'mistral-7b',
    hfId: 'mistralai/Mistral-7B-Instruct-v0.3',
    display_name: 'Mistral 7B v0.3',
    is_moe: false,
    total_params: 7_241_000_000,
    active_params: 7_241_000_000,
    num_layers: 32,
    d_model: 4096,
    num_q_heads: 32,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(32, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'mistral-small-24b',
    hfId: 'mistralai/Mistral-Small-Instruct-2409',
    display_name: 'Mistral Small 24B',
    is_moe: false,
    total_params: 23_570_000_000,
    active_params: 23_570_000_000,
    num_layers: 40,
    d_model: 5120,
    num_q_heads: 32,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(40, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'mixtral-8x7b',
    hfId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    display_name: 'Mixtral 8x7B',
    is_moe: true,
    total_params: 46_700_000_000,
    active_params: 12_900_000_000,
    num_experts: 8,
    experts_per_token: 2,
    num_layers: 32,
    d_model: 4096,
    num_q_heads: 32,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(32, 8, 128, 1),
    geometry_source: 'known',
  },
  // ── Qwen family ───────────────────────────────────────────────────────────────
  {
    id: 'qwen3-8b',
    hfId: 'Qwen/Qwen3-8B',
    display_name: 'Qwen3-8B',
    is_moe: false,
    total_params: 8_190_000_000,
    active_params: 8_190_000_000,
    num_layers: 36,
    d_model: 4096,
    num_q_heads: 32,
    num_kv_heads: 8,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(36, 8, 128, 1),
    geometry_source: 'known',
  },
  {
    id: 'qwen3-30b-a3b',
    hfId: 'Qwen/Qwen3-30B-A3B',
    display_name: 'Qwen3-30B-A3B',
    is_moe: true,
    total_params: 30_500_000_000,
    active_params: 3_300_000_000,
    num_experts: 128,
    experts_per_token: 8,
    num_layers: 48,
    d_model: 2048,
    num_q_heads: 32,
    num_kv_heads: 4,
    head_dim: 128,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(48, 4, 128, 1),
    geometry_source: 'known',
  },
  // ── NVIDIA ────────────────────────────────────────────────────────────────────
  {
    id: 'nemotron-4-340b',
    hfId: 'nvidia/Nemotron-4-340B-Instruct',
    display_name: 'Nemotron-4 340B',
    is_moe: false,
    total_params: 340_000_000_000,
    active_params: 340_000_000_000,
    num_layers: 96,
    d_model: 18432,
    num_q_heads: 96,
    num_kv_heads: 8,
    head_dim: 192,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(96, 8, 192, 1),
    geometry_source: 'known',
  },
  // ── ZhipuAI GLM-5 ─────────────────────────────────────────────────────────────
  // Full MHA (no GQA). DSA head_dim unverified — KV budget approximate.
  {
    id: 'glm-5.1',
    display_name: 'GLM-5.1 (754B)',
    is_moe: true,
    total_params: 754_000_000_000,
    active_params: 40_000_000_000,
    num_experts: 256,
    experts_per_token: 8,
    num_layers: 78,
    d_model: 6144,
    num_q_heads: 64,
    num_kv_heads: 64,
    head_dim: 64,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(78, 64, 64, 1),
    geometry_source: 'estimated',
  },
  {
    id: 'glm-5.2',
    display_name: 'GLM-5.2 (753B)',
    is_moe: true,
    total_params: 753_000_000_000,
    active_params: 40_000_000_000,
    num_experts: 256,
    experts_per_token: 8,
    num_layers: 78,
    d_model: 6144,
    num_q_heads: 64,
    num_kv_heads: 64,
    head_dim: 192,
    kv_dtype_bytes: 1,
    kv_bytes_per_token: kv(78, 64, 192, 1),
    geometry_source: 'estimated',
  },
  // ── Internal / reference ──────────────────────────────────────────────────────
  {
    id: 'gpt-oss-20b',
    display_name: 'GPT-OSS 20B (MoE)',
    is_moe: true,
    total_params: 20_900_000_000,
    active_params: 3_610_000_000,
    num_experts: 32,
    experts_per_token: 4,
    num_layers: 24,
    d_model: 2880,
    num_q_heads: 64,
    num_kv_heads: 8,
    head_dim: 64,
    kv_dtype_bytes: 1,
    resident_weights_gb: 13.0,
    kv_bytes_per_token: kv(24, 8, 64, 1),
    geometry_source: 'known',
  },
]

export function getRooflineModelById(id: string): RooflineModel | undefined {
  return ROOFLINE_MODEL_CATALOG.find(m => m.id === id || m.hfId === id)
}

/**
 * Build a RooflineModel from a HuggingFace config.json.
 * Used when the user types a model ID not in the static catalog.
 * geometry_source is 'estimated' — confidence band widens to ±25%.
 */
export function hfConfigToRooflineModel(hfId: string, cfg: HFModelConfig): RooflineModel {
  const d_model      = cfg.hidden_size         ?? 4096
  const num_layers   = cfg.num_hidden_layers   ?? 32
  const H_q          = cfg.num_attention_heads ?? 32
  const H_kv         = cfg.num_key_value_heads ?? H_q
  const head_dim     = (cfg.head_dim as number | undefined) ?? Math.round(d_model / H_q)
  const ffn_dim      = cfg.intermediate_size   ?? (4 * d_model)
  const vocab_size   = cfg.vocab_size          ?? 32_000
  const num_experts  = cfg.num_local_experts   ?? 1
  const experts_per_token = cfg.num_experts_per_tok ?? 1
  const is_moe       = num_experts > 1

  // Attention params — GQA-correct: Q(d×H_q×head_dim) K(d×H_kv×head_dim) V K O
  const attn_per_layer = d_model * head_dim * (2 * H_q + 2 * H_kv)

  // FFN — SwiGLU uses 3 matrices (gate + up + down)
  const ffn_per_expert = 3 * d_model * ffn_dim
  const ffn_per_layer  = num_experts * ffn_per_expert

  // Embeddings (assume tied)
  const embed = vocab_size * d_model

  const total_params = embed + num_layers * (attn_per_layer + ffn_per_layer)
  const active_params = is_moe
    ? embed + num_layers * (attn_per_layer + experts_per_token * ffn_per_expert)
    : total_params

  const kv_dtype_bytes = 2  // bf16 KV cache default
  const kv_bytes_per_token = kv(num_layers, H_kv, head_dim, kv_dtype_bytes)

  return {
    id: hfId,
    hfId,
    display_name: hfId.split('/').pop() ?? hfId,
    is_moe,
    total_params,
    active_params,
    num_layers,
    d_model,
    num_q_heads: H_q,
    num_kv_heads: H_kv,
    head_dim,
    kv_dtype_bytes,
    kv_bytes_per_token,
    geometry_source: 'estimated',
    ...(is_moe ? { num_experts, experts_per_token } : {}),
  }
}
